### ISSUE TITLE
Failed to install 'de.neofonie.cordova.plugin.nativeaudio':CordovaError: Uh oh!

### ISSUE THREAD

**Issue by pandres95** [floatinghotpot/cordova-plugin-nativeaudio#77]
"Uh oh!"?

```
Failed to install 'de.neofonie.cordova.plugin.nativeaudio':CordovaError: Uh oh!
"/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/plugins/de.neofonie.cordova.plugin.nativeaudio/src/ios/NativeAudio.m" not found!
    at copyFile (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/lib/plugman/pluginHandlers.js:261:36)
    at copyNewFile (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/lib/plugman/pluginHandlers.js:293:5)
    at installHelper (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/lib/plugman/pluginHandlers.js:212:9)
    at handlers.source-file.install (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at Object.ActionStack.process (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.addPlugin (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/lib/plugman/Plugman.js:82:20)
    at Api.addPlugin (/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/platforms/ios/cordova/Api.js:187:53)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:601:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:385:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
"/Users/pandres95/Documents/Bool/Development/Projects/Tandembox/mobile/plugins/de.neofonie.cordova.plugin.nativeaudio/src/ios/NativeAudio.m" not found!
```

Is it me, who didn't download the files well, or is it something else. I need help!

**Comment by floatinghotpot** [comment]
What is `de.neofonie.cordova.plugin.nativeaudio`? 

Please try `cordova-plugin-nativeaudio`!!

**Comment by pandres95** [comment]
As indicated in my `config.xml`

```
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
    <plugin name="cordova-plugin-console" spec="~1.0.2" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~1.6.1" />
    <plugin name="cordova-plugin-device" spec="~1.1.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.2.1" />
    <plugin name="cordova-plugin-iosrtc" spec="~2.2.3" />
    <plugin name="cordova-plugin-splashscreen" spec="~3.1.0" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.1" />
    <plugin name="cordova-plugin-brightness" spec="~0.1.5" />
    <plugin name="cordova-plugin-nativeaudio" spec="~3.0.6" />
    <plugin name="cordova-plugin-x-toast" spec="~2.5.0" />
    <plugin name="cordova-plugin-insomnia" spec="https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
    <preference name="xwalkMode" value="embedded" />
    <preference name="xwalkMultipleApk" value="true" />
</widget>
```

I'm using `cordova-plugin-nativeaudio@3.0.6`. Please, help me. I'm desperate :cry:

**Comment by floatinghotpot** [comment]
So the error message about `de.neofonie.cordova.plugin.nativeaudio` is weird. 

Can you create a clean cordova project?

**Comment by pandres95** [comment]
Sorted!

It seems I had a registry referring to `de.neofonie.cordova.plugin.nativeaudio` on my `plugins/fetch.json` file.
